" Use the Solarized Dark theme
syntax enable
set background=dark
" solarized options 
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
let g:solarized_itermcolors = 256
colorscheme solarized
